##sparql --results=CSV --data=../resources/be/vlaanderen/omgeving/data/id/conceptscheme/observatieprocedure/observatieprocedure.ttl  --query rdf_to_csv.rq > ../resources/be/vlaanderen/omgeving/data/id/conceptscheme/observatieprocedure/observatieprocedure.csv


prefix skos:  <http://www.w3.org/2004/02/skos/core#>
prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
prefix dcat:   <http://www.w3.org/ns/dcat#>

select distinct
?type
?uri
?notation
?prefLabel
?altLabel
?definitions
(group_concat(?collection;separator="|") as ?collections)
?inScheme
?themes
?seeAlso
?topConceptOf
where
{
select distinct
?type
?uri
?notation
?prefLabel
?altLabel
?definitions
?collection
?inScheme
(group_concat(?theme;separator="|") as ?themes)
?seeAlso
?topConceptOf
where
{
select distinct
?type
?uri
?notation
?prefLabel
?altLabel
(group_concat(?definition;separator="|") as ?definitions)
?collection
?inScheme
?theme
?seeAlso
?topConceptOf
where
{
select distinct
?type
?uri
?notation
?prefLabel
?altLabel
?definition
?collection
?inScheme
?theme
?seeAlso
?topConceptOf
where 
{?uri
a ?type .
optional {?uri skos:definition ?definition }
optional {?uri skos:inScheme ?inScheme }
optional {?uri skos:notation ?notation }
optional {?uri skos:prefLabel ?prefLabel }
optional {?uri skos:altLabel ?altLabel }
optional {?uri rdfs:seeAlso ?seeAlso .}
optional {?uri dcat:theme ?theme .}
optional {?uri skos:topConceptOf ?topConceptOf .}
optional {?uri a skos:Concept . ?collection skos:member ?uri .}
}
GROUP BY ?type ?uri ?notation ?prefLabel ?altLabel ?definition ?collection ?inScheme ?theme ?seeAlso ?topConceptOf
ORDER BY ?definition
}
GROUP BY ?type ?uri ?notation ?prefLabel ?altLabel ?collection ?inScheme ?theme ?seeAlso ?topConceptOf
ORDER BY ?theme
}
GROUP BY ?type ?uri ?notation ?prefLabel ?altLabel ?collection ?inScheme ?seeAlso ?topConceptOf ?definitions
ORDER BY ?collection
}
GROUP BY ?type ?uri ?notation ?prefLabel ?altLabel ?inScheme ?themes ?seeAlso ?topConceptOf ?definitions
ORDER BY ?uri