prefix skos:  <http://www.w3.org/2004/02/skos/core#>
prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> 
prefix dbo:   <http://dbpedia.org/ontology/> 
prefix cs:    <https://data.vlaanderen.be/ns/chemische_stof#> 
prefix dbp:   <http://dbpedia.org/property/>
prefix dct:   <http://purl.org/dc/terms/>
prefix dcat:  <http://www.w3.org/ns/dcat#>

select distinct
?uri
?notation
?prefLabel
?altLabel
?definition
?casNumber
?references
?collection
?theme
?seeAlso
?member
?type
where 
{?uri a ?type .
optional {?uri skos:altLabel ?altLabel }
optional {?uri skos:definition ?definition }
optional {?uri skos:notation ?notation }
optional {?uri skos:prefLabel ?prefLabel }
optional {?uri skos:altLabel ?altLabel }
optional {?uri dbo:casNumber ?casNumber }
optional {?uri dct:references ?references}
optional {?uri rdfs:seeAlso ?seeAlso .}
optional {?collection skos:member ?uri .}
optional {?uri skos:member ?member .}
optional {?uri dcat:theme ?theme .}
}


